"$schema" = "https://unpkg.com/wrangler@latest/config-schema.json"
name = "cloudflare-worker-template"
main = "src/worker.ts"
compatibility_date = "2026-04-25"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "test_db"
database_id = "xxxxxxxx-xxxxxxxxxx-xxxxxxx"
migrations_dir = "drizzle"

# --- STAGING ENVIRONMENT ---

[env.staging]
name = "cloudflare-worker-template-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "test_db_staging"
database_id = "c32ddb8d-7b40-4a2e-8b99-69967100fcb7"
migrations_dir = "drizzle"
